### PR TITLE
Fix build without ZeroEQ after #34

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by rdumusc** [comment]
...this time I'm going to wait on travis before merging

**Comment by rdumusc** [comment]
ping - can merge?

**Comment by tribal-tec** [comment]
Update the travis.yml to also have ZeroEQ dependency on OSX?

**Comment by rdumusc** [comment]
Why not, this can be an incentive to fix the http server on OSX (currenty it kind of deadlocks on the first request)

**Pull request merged**
