### PR TITLE
Upgrade from QtWebKit to QtWebEngine [DISCL-366]

### PR DESCRIPTION
**Pull request by rdumusc**
Know issues:
- Works well with Qt 5.6.1, although it is not entirely stable
  (it still crashes occasionally for unclear reasons).
- With Qt 5.4.1, it has some issues with https and webgl interaction.

### CODE REVIEW

**Comment by rdumusc** [comment]
The crash observed is unrelated to the Webbrowser changes.
It is a Qt 5.6.1 bug, which can be reproduced on Ubuntu with the phone TUIO simulator and interacting "hard" with any (pixelstream?) window with multiple touch points. After some time, a segfault is triggered in QV4::QmlContextWrapper::get().
I have not found any way to fix the problem so far, but I'm going to evaluate different Qt versions (5.5.1, 5.7.0) to see if this still happens.

**Comment by rdumusc** [comment]
Updated release notes with the know issues and created issue #80

**Comment by tribal-tec** [comment]
As discussed, make WebEngine available via an option.
+1 otherwise

**Comment by rdumusc** [comment]
Added TIDE_ENABLE_WEBENGINE option, OFF by default

**Pull request merged**
