### PR TITLE
Load and save sessions asynchronously [DISCL-359]

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Nice feature!
To me it's a bit risky to include in the release, it's your call if you're confident. While the session is being loaded, the UI stays fully operational I guess, so a user can issue loading of several sessions or do other stuff in the UI which potentially conflicts with the background loading?

**Comment by rdumusc** [comment]
Yes, it is possible to issue successive calls if the loading takes a lot of time.
In theory a second call will block until the first one is finished, so it won't do much harm. But this has to be tested to make sure it works well in practice. Saving a session is safe and seem to work well, but the unit tests for loading cause a deadlock right now so I am trying to come up with a slightly safer solution.

**Comment by rdumusc** [comment]
Updated with a different approach to avoid any risk of deadlocking the main QEventLoop. The launcher also closes everything before sending the load command to provide immediate feedback before the loading happens in the background. This has to be tested on the real wall, but I am quite confident about this change. If this is not working well for users, we can always make the load blocking again by just waiting on the future.

**Comment by tribal-tec** [comment]
+1

**Pull request merged**
