### PR TITLE
[Example] Tide and Spack integration for combinatorial builds

### PR DESCRIPTION
**Pull request by pramodskumbhar**
Prototype that shows how Spack could be setup for
 - building multiple versions of softwares
 - with multiple compilers
 - with multiple dependencies and their versions
 - for multiple platforms
 - Travis/Jenkins/Development workflow integration

P.S. This PR is only as an example

### CODE REVIEW

**Comment by pramodskumbhar** [comment]
Hi Raphael & Viz Team,

This example is follow up of our discussion with some of you. This is "bit" too long but I thought I should this to give detailed overview. I thought PR will be more suitable for comments / code references. 

#### Background

Most of users were using Lugano viz-cluster and it was "sufficient" to deploy stack with one compiler and MPI. With the new system we will soon have:

- KNL partition 
- Pascal/Volta GPU parition
- Skylake Partition
- Geneva cluster (will have older/newer CPUs)
- HBP systems (JURON - Power8, Julia - KNL, CSCS-Haswell/Skylake/GPUs)

And in two years we will upgrade some part of the cluster.  Whenever we have to deploy our softwares on external system, above situation is not uncommon.

For the performance engineering related work I have been working with external computing centres. I thought it might be helpful to share some of the development related to build systems in this area.

I don't have complete knowledge and understanding of your software stack. Some of the examples/use cases below may not be applicable for you. In this case, please ignore my lack of knowledge.

#### "Ideal" Goals

One can deploy same software stack [one compiler/one mpi] across architecturs but this "somewhat" defeats the purpose of different architectures (of course this depends on case to case basis). But for above mentioned architectures, in "ideal" scenario vendors (and hpc centres) do:

- KNL partition: softwares to be deployed with Intel compiler, Intel MPI, Intel Python (Intel MKL for BLAS/Lapack)
- Pascal/Volta GPU partition : softwares with MVAPICH2 (CUDA/GPUDirect aware), GCC/Intel compiler
- Pscal/Volta GPU : For new programming model support use PGI / Cray compiler (often with their own MPI library)
- Power8 nodes [in Geneva soon] : with XL compiler with IBM MPI / OpenMPI
- Remaining partitions with regular stack (gcc/intel + mvapich2/intelmpi etc.)

Developing/deploying software in such a way is painful for developers as well as end users. But for CI/developing/benchmarking/deployment, it would be useful if we could "easily" build:

- different versions of software
- with different versions of compilers
- with different MPI libraries
- on different platforms/architectures
- with different build options (with/without mpi, static/shared, with/without boost, qt etc)

I know this is too much and we don't want N^2 combinations. But at least few meaningful ones. This problem of combinatorial build is common in scientific computing and Spack project was started to address this. I have been using/evaluating Spack which I describe next. 

#### Why Spack ?

In scientific computing we frequently need different versions and configurations of softwares to test the performance and compatibility. Traditional package managers are limiting because they cannot manage simultaneous installations of multiple versions and dynamic configurations. [Spack](https://github.com/LLNL/spack) is a flexible, configurable, Python-based package manager, automating the installation and fine-tuning of simulations and libraries. It is designed for wide variety of HPC architectures and can install many variants of the same build using different compilers, options, and Message Passing Interface (MPI) implementations. Spack is being developed and supported by various scientific computing centres (including major DOE labs). There are more than 2000 packages contributed by different users and growing rapidly.

Instead of looking at magic commands to install external packages, as a developer we want to understand how we can package our own software. Can we easily understand and use it during daily development? Many package managers have their own programming language and workflows. In my opinion Spack is much more approachable.

I think best approach is to use one of the package as an example. With the help of Raphael ,I am using Tide here. 
 
#### Creating Spack Package

When we install Tide, we notice following :

- build dependnecies : cmake 
- link dependencies (more like libraries)  : MPI, Qt , Boost , libjpeg-turbo, ffmpeg
- link dependencies (our other softwares ) : tuio, zeroeq, deflect, virtualkeyboard

And then we do:

```bash
git clone --recursive https://github.com/BlueBrain/Tide
mkdir Tide/build && cd Tide/build
cmake .. -DCLONE_SUBPROJECTS=ON
make && make install
```

Turning these instructions into Spack package is easy: we create python file `package.py` that looks like:

```python
from spack import *

class Tide(Package):

    homepage = "https://github.com/BlueBrain/Tide"
    url      = "https://github.com/BlueBrain/Tide.git"

    version('develop', git=url, submodules=True)

    depends_on('mpi')
    depends_on('ffmpeg')
    depends_on('zeromq')
    depends_on('qt')
    depends_on('boost')
    depends_on('libjpeg-turbo')
    depends_on('cmake', type='build')

    def install(self, spec, prefix):
        args = ['-DCLONE_SUBPROJECTS=ON']
        with working_dir("build", create=True):
            cmake('..', *args)
            make()
            make('install')
```

The package is self explanatory, written in Python with some syntactic sugar: 

- `version` clause specify name of version (`develop`) and git repository with submodules to clone.
- `depends_on` clause is used to specify dependencies. 
- `install` method is called during installation. The methods like  `install` are provided by Spack's `Package` base class that execute actual commands.

In this first basic example we are still using `-DCLONE_SUBPROJECTS`. Ideally we want dependencies to build as separate package. We can create similar `package.py` file for those packages. For example, here is an example for `deflect`:

```python
from spack import *

class Deflect(Package):

    homepage = "https://github.com/BlueBrain/Deflect"
    url      = "https://github.com/BlueBrain/Deflect.git"

    version('develop', git=url, submodules=True)

    depends_on('qt')
    depends_on('boost')
    depends_on('libjpeg-turbo')
    depends_on('cmake, type='build')
    
    def install(self, spec, prefix):
    	...   
``` 

>  who is writing packages for qt, boost? Most of the common packages are contributed by community. More than 2000 packages are provided by Spack (e.g. [Boost](https://github.com/LLNL/spack/blob/18c7e9662437081e4d283abf656e1604228af045/var/spack/repos/builtin/packages/boost/package.py)).

Once we have dependent packages, we can update Tide package as:

```python
class Tide(Package):

    homepage = "https://github.com/BlueBrain/Tide"
    url      = "https://github.com/BlueBrain/Tide.git"

    version('develop', git=url, submodules=True, preferred=True)

    depends_on('mpi')
    depends_on('deflect')
    depends_on('qt')
    depends_on('boost')
    depends_on('libjpeg-turbo')

    depends_on('zeroeq')
    depends_on('tuio')
    depends_on('ffmpeg')
    depends_on('virtualkeyboard')
    depends_on('cmake@3:', type='build')

    ... 
   #(can use now -DDISABLE_SUBPROJECTS=ON)
   
```

With this if issue `spack install tide` command then Spack will install first it's dependencies and then Tide.

#### **But, if we are using other package manager, what are we gaining here with Spack?**

During daily development on desktop/clusters we come across following situations:

- (if require) one can install tide with or without : zeroeq, tuio, ffmpeg, virtualkeyboard
	- we want to enable/disable zeroeq, tuio, ffmpeg, virtualkeyboard without hardcoding into package recipe
- we want to choose version of MPI library (at build time)
- we want to choose compiler (at build time)
- we want to choose platform specific options (e.g. for KNL architecture should add '-xMIC-AVX512' flag with Intel compiler. Same for Cray/BG-Q/Power8 platform)
- if user report bug with certain compiler/mpi version then we want to reproduce the issue locally
- want to build latest master of tide and it's dependencies? Or, last released versions with new compiler version?

To accommodate above requirements we can update Tide package as below. There are `shorthands` for writing this but I am writing all explicitly for clarity:

```python
from spack import *
import os

class Tide(CMakePackage):

    homepage = "https://github.com/BlueBrain/Tide"
    url              = "https://github.com/BlueBrain/Tide.git"

    version('1.3.1',   git=url, tag='1.3.1', submodules=True)
    version('1.3.0',   git=url, tag='1.3.0', submodules=True)
    version('develop', git=url, submodules=True, preferred=True)

    variant('touch',    default=True,  description="Enable TUIO touch listener")
    variant('movie',    default=True,  description="Enable FFMPEG movie support")
    variant('rest',     default=True,  description="Enable REST interface using ZeroEQ")
    variant('keyboard', default=True,  description="Enable virtual keyboard support")
    variant('knl',      default=False, description="Compile for KNL architecture")

    depends_on('mpi')
    depends_on('deflect')
    depends_on('qt@5.4:')
    depends_on('boost@1.54:')
    depends_on('libjpeg-turbo')

    depends_on('zeroeq', when='+rest')
    depends_on('tuio',   when='+touch')
    depends_on('ffmpeg', when='+movie')
    depends_on('virtualkeyboard', when='+keyboard')
    depends_on('cmake@3:', type='build')

    @run_before('cmake')
    def common_cxx11_abi_check(self):
        if self.spec.satisfies('%gcc@5:'):
            os.environ["CMAKE_COMMON_USE_CXX03_ABI"] = "1"

    def get_knl_flag(self, spec):
        flags = ""
        if spec.satisfies('%gcc'):
            flags = "-march=knl -mavx512f -mavx512pf -mavx512er -mavx512cd"
        elif spec.satisfies('%intel'):
            flags = "-xMIC-AVX512"
        return flags

    def cmake_args(self):
        spec = self.spec
        args = ['-DDISABLE_SUBPROJECTS=ON']
        args.extend(['-DTIDE_ENABLE_MOVIE_SUPPORT=%s'       % ('ON' if '+movie' in spec else 'OFF'),
                     '-DTIDE_ENABLE_REST_INTERFACE=%s'      % ('ON' if '+rest' in spec else 'OFF'),
                     '-DTIDE_ENABLE_TUIO_TOUCH_LISTENER=%s' % ('ON' if '+touch' in spec else 'OFF')])
        if '+knl' in spec:
            flags = get_knl_flag()
            args.append('-DCMAKE_C_FLAGS=%s' % flags)
            args.append('-DCMAKE_CXX_FLAGS=%s' % flags)

        return args

    def setup_environment(self, spack_env, run_env):
        spec = self.spec
        run_env.set('IPATH_NO_CPUAFFINITY', 1)
        if not spec.satisfies('^openmpi'):
            run_env.set('MV2_ENABLE_AFFINITY', 0)
        
```

Spack use following notations  worth mentioning:

- `@` symbol is used to specify version
- `^` symbol is used to specify dependency
- `%` symbol is used to specify compiler
- `+` symbol to turn-on variant and `-` or `~` to turn-off

We can understand more or less what's going on. The `spec` object is something that has information about package being installed, its dependencies, compilers, architecture etc. We can query different information using `spec`:

- `+rest in spec` : is rest option enabled by user
- `-rest in spec` : is rest option disabled by user
- `spec.satisfies('%gcc')` : are we building with gcc compiler
- `'ppc64le' in spec.architecture` : are we building on powerpc64 little endian system? (Power 8)
- `spec.satisfies('^openmpi') : is openmpi in our dependency?
- etc...

Also you can use all python modules/methods. Here are notable changes from previous version:

- we are using `CMakePackage` base class which provides basic methos like `cmake`, `make`, `make install` for CMake based projects. Instead of install method we can just override `cmake_args` method to return arguments to CMake. Rest (make, make install) will be handled by CMakePackage class.
- we have now added multiple versions (github tags with md5 checksums) 
- options using `variant` : variants are more like switches that can be turned on or off. (we will see how to use them)
- dependencies with `depends_on` keywords have additional `when` clause. We say `depends_on('zeroeq', when='+rest')`: this means we are dependent on zeroeq only if we have enabled `rest` option (option naming `rest` here is user defined)
- note that `@` is used to specify version with `:` as separator for min/max version (`qt@5.4:5.8` means any qt version >= 5.4 and <= 5.8 is acceptable)
- we have explicitly specified cmake depndency as `type='build'`. (will see why that matters in cross-compiling section)
- we have added `knl` as variant. If user turn on this variant, we add KNL specific flags.
- before running cmake command, we check if are building with gcc > 5 and set `CMAKE_COMMON_USE_CXX03_ABI` env variable (you set that in your env module)
- we added dependency to `mpi` and not actual implementations like `mpich`, `mvapich2`, `openmpi` etc. This is because laters act as provider of `mpi`. We called `mpi` virtual dependency which could be mpich, mvapich2, openpi, intel-mpi etc. Later we see how to use it.
- Spack has inbuilt support for automatic modules generation and `setup_environment` method is used for setting user environment in modules file. (will see later)

There are lots of other options for advanced use cases. Spack provided different methods to package Makefile, Autotools, CMake and Python based projects. More information can be found in [Packaging Guide](http://spack.readthedocs.io/en/latest/packaging_guide.html).

Now we put lots of logic in package recipe. Next question is how to use it?

#### Installing Tide

We have already mentioned following notations:

- `@` symbol is used to specify version
- `^` symbol is used to specify dependency
- `%` symbol is used to specify compiler
- `+` symbol to turn-on variant and `-` or `~` to turn-off

Here is how we can now install Tide:

- Install develop version: 

```
spack install tide@develop
```

- Install version 1.3.1 with intel compiler and KNL specific flag: 

```
spack install tide@1.3.1 +knl %intel
```

- Install version 1.3.1 with gcc 6.2 compiler and openmpi: 

```
spack install tide@1.3.1 %gcc@6.2 ^openmpi
```

- Install develop version using gcc 6.2 without rest, touch, keyboard, movie support:

```
spack install tide@develop -rest -touch -keyboard -movie %gcc@6.2
```

- Install develop version of deflect using 0.13.0 version of deflect

```
spack install tide@develop ^deflect@0.13.0
```

- Install using debug build:

```
spack install tide@develop build_type=Debug
```

- Install with intel 2017 compiler and Intel MPI:

```
spack install tide@develop  %intel@17 ^intelmpi
```

- Install Tide and all dependencies from latest github master branch:

```
spack install tide@develop +keyboard +movie +touch +rest ^deflect@develop ^virtualkeyboard@develop ^tuio@develop ^zeroeq@develop ^servus@develop
```

- One of the most annoying issue using vendor compilers: often commercial compilers (PGI, Cray, Intel) can't compile many open source packages. (there is an issue with with Zeroeq as well). In this case we want to install Tide with Intel but Zeroeq with GCC. This is as simple as:

```
spack install tide@develop +keyboard +movie +touch +rest %intel@17 ^deflect@develop ^zeroeq@develop %gcc@4.9.0 ^servus@develop
```
Spack will `"concretise"` dependencies such that zeroeq and all its dependecies will be installed with GCC 4.9.0 but rest with Intel.

Note that if any dependencies like OpenMPI are not available on system, Spack can/will install them.

Using this in practice seems complicated but one of the strong point of Spack is command line support to understand what's going beneath. That's where `spack spec` command useful.

#### Understanding details with "spack spec"

Before installing anything we must understand what's going to be installed. Spack spec command precisely shows that:

spack_spec_tide

Here are some details:

- Input spec is what we provide on command line
- Normalised is something that Spack find out looking at all dependencies
- Concretised is how/what Spack will install considering available compilers, architecture, dependencies

If you follow DAG we see precisely what is going to be installed, their versions, compilers, architectures and variants. More than 40 packages will be downloaded and installed from source. This will take more than hour. Our Travis builds will never finish!

And, we want to install this all with 4-5 different compilers, 3-4 MPI versions and options? We will add another 500 modules and 5 million files to viz cluster! 

Some package managers use `binary cache` but this doesn't work well when we have multiple architectures, cross-compiling environment, different compilers and vendor provided libraries. This has been major drawback with existing package managers in scientific computing.

In practice, we (almost) never want to install pkg-config, m4, tar etc from source. They are already installed on system. Same apply for Boost, MPI, Qt which already installed on our desktop or present as modules on cluster. We just want to use those!

One of the most important design aspect of Spack is flexibility to integrate with existing ecosystem. For example:

- while building on OS X, we want to use exisiting system installed packages or packages installed using brew/macports
- on desktop we want to use yum/apt-get to install standard packages
- on hpc clusters, we want to use exisiting modules, compilers, mpi libraries provided by sysadmins or vendors
- and if there is something missing, we want ability to install missing packages from source

Spack provides simple interface to achieve this: we just create yaml file (`$HOME/.spack/packages.yaml`) specifying which packages are already installed, their versions and paths (or modules):

```
packages:
    mpich:
        paths:
            mpich@3.0.4: /usr/local
        buildable: False 
        version: [3.0.4]
    openmpi:
        paths:
            openmpi@2.1.1: /usr/local
        buildable: False
        version: [2.1.1]
    cmake:
        paths:
            cmake@3.9.1: /usr/local
        buildable: False
        version: [3.9.1]
    boost:
        paths:
            boost@1.61: /usr/local/opt/boost
        buildable: False
        version: [1.61]
    zeromq:
        paths:
            zeromq@4.2.2: /usr/local/opt/zeromq
        buildable: False
        version: [4.2.2]
    libjpeg-turbo:
        paths:
            libjpeg-turbo@1.5.2: /usr/local/opt/jpeg-turbo
        buildable: False
        version: [1.5.2]
    qt:
        paths:
            qt@5.9.1: /usr/local/opt/qt
        buildable: False
        version: [5.9.1]
    ffmpeg:
        paths:
            ffmpeg@3.3.4: /usr/local/opt/ffmpeg
        buildable: False
        version: [3.3.4]
```

We have these config files for Lugano viz cluster [here](https://github.com/pramodskumbhar/spack-packages/blob/tide_proto/sysconfigs/bbpviz/packages.yaml) and travis [here](https://github.com/pramodskumbhar/Tide/blob/travis_spack/.travis/packages.osx.yaml). With this file in place, `spack spec -I tide` now shows:

spack_spec_tide_installed


> I am maintaining different [system specific configuration files](https://github.com/pramodskumbhar/spack-packages/tree/develop/sysconfigs) for different HPC systems.

Packages which are already present are indicated with `+`. Now we are going to install what we care about. Similarly we can see what happens when we disable certain variants:

spack_spec_tide_intel

Once we understand what is getting installed, we can replace `spec` by `install` command.

This works nicely on desktop or large hpc systems where we have to use existing software stack provided by HPC centres. This avoids installation of large number of unnecessary packages. 

The last scenario is special: **Cross Compiling Environment**

Brief: In cross compiling environment we want `"build"` dependencies like CMake to be compiled for front-end architecture but rest of `"link"` dependencies to be built for back-end node architecture. Today we have direct access to nodes and can compiler software stack direct login on the node. But this not the case when we go on many external systems. Spack distinguish different dependency types and architectures. We can specify architecture constraints on command line to say build cmake for one architecture and rest for another architecture. Here is quick output on BG-Q:

spack_spec_tide_bgq

If we look at the DAG, we are building CMake with GCC for Power7 architecture of login node and rest with XL compiler for powerpc64 architecture of compute nodes. Important part is that this information is not hardcoded anywhere in Tide package or dependencies. Spack has `concretiser` that dynamically `concretise` packages for constraints provided on command line (depending on architecture, compilers, dependencies). Newer machines are `kind` of cross-compiling architectures (with combination of Haswell, Skylake, KNL, Power8, GPUs etc). So this is becoming more important.

#### Discovering/Using/Removing Spack packages

Once we install packages we can use different spack commands to find :

- `spack find tide` : find all tide packages
- `spack find --variants tide %gcc` : compiled with gcc and show variants
- `spack find --deps tide ^intelmpi` : built with intelmpi and show all dependencies as well
- `spack find ^deflect` : all depen on deflect
- `spack uninstall %intel` : uninstall all packages built with Intel compiler
- `spack load tide@develop %intel` : load develop version compiled with intel compiler

Here are some examples:

spack_find
spack_find_v
spack_find_deps

There many other commands, see [user guide (https://spack.readthedocs.io/en/latest/basic_usage.html).

#### Spack for end users

Above we have seen Spack commands only. But most of us (and our users) are already familiar with `Environment Modules` i.e. `module load tide`. When we deploy Tide for end users, we need to create modules. Spack has in-built support for generating modules. This means, when we install specific version of Tide, module is automatically created! For example, here are autogenerated modules from above comamnd:

spack_module_avail

The generate module file looks like (see environment variables which we set in `setup_environment` method of `package.py` get inserted into module):

spack_module_sample

We don't write any code for modules generation. But one can provide extra configuration about how module file should look, naming conventions etc. The confg file modules is [modules.yaml](https://github.com/pramodskumbhar/spack-packages/blob/tide_proto/sysconfigs/bbpviz/modules.yaml).


#### Spack in Continious Intgeration / Development?

During the developlment we want to build locally cloned version. For travis / Jenkins CI, we wan to build the branch/PR already cloned. In this case, we just have to add path of directory as Spack version:

```
    version('develop', git=file:////Users/travis/tide)

```

And now `spack install tide@develop` will install from local directory. This is how we build build [pull request](https://github.com/pramodskumbhar/Tide/blob/51c19f7d1b49c6612121b1ca57fd691746851165/.travis/install_tide.sh#L41). 

> Note: there is another evolving [development workflow](https://spack.readthedocs.io/en/latest/workflows.html#developing-software-with-spack) in Spack which is bit more advance but still under active development.

#### How easy to setup all this?

From my experience, Spack is easy to setup/configure compared to other solutions. It is just python program and doesn't need anything extra setup. We need basic utilities like python, git, curl. Jenkins plan that I have [setup for Tide](https://bbpcode.epfl.ch/ci/view/sim/job/incubator.tide/) is something like this:

```
git clone --depth 1 https://github.com/pramodskumbhar/spack.git -b stable
git clone --depth 1 https://github.com/pramodskumbhar/spack-packages.git -b tide_proto

export SPACK_ROOT=`pwd`/spack
export PATH=$SPACK_ROOT/bin:$PATH
source $SPACK_ROOT/share/spack/setup-env.sh

spack repo add --scope site ./spack-packages

# list of packages
packages=(
           "tide@develop -keyboard -movie -touch -rest %gcc@6.2.0 ^deflect@develop"
           "tide@develop -keyboard -movie -touch -rest %intel@17 ^deflect@develop"
           "tide@develop +keyboard +movie -touch -rest %intel@17 ^deflect@develop"
           "tide@develop +keyboard +movie +touch +rest %gcc@4.9.0 ^deflect@develop ^zeroeq@develop ^servus@develop"
           "tide@develop +keyboard +movie +touch +rest %gcc@6.2.0 ^deflect@develop ^zeroeq@develop ^servus@develop"
           "tide@develop +keyboard +movie +touch +rest %intel@17 ^deflect@develop ^zeroeq@develop %gcc@4.9.0 ^servus@develop"
)

# build all packages using spack
for package in "${packages[@]}"
do
    spack install $package
done

```

You can see all above output/screenshots that are part of [this jenkins output log](https://bbpcode.epfl.ch/ci/view/sim/job/incubator.tide/825/console).

Travis CI plan also shows same workflow:

- First we install necessary softwares using brew or apt-get (e.g. [install_dependencies.sh](https://github.com/pramodskumbhar/Tide/blob/travis_spack_proto/.travis/install_dependencies.sh))
- We create packages.yaml telling which packages are pre-installed (e.g. [packages.yaml](https://github.com/pramodskumbhar/Tide/blob/travis_spack_proto/.travis/packages.linux.yaml))
- We clone Spack repository and setup environment / PATH (e.g. [setup_spack.sh](https://github.com/pramodskumbhar/Tide/blob/travis_spack_proto/.travis/setup_spack.sh))
- And we install Tide packages (e.g. [install_tide.sh](https://github.com/pramodskumbhar/Tide/blob/travis_spack_proto/.travis/install_tide.sh))

And this is same on mac, desktop, cluster or any supercomputer.  Travis log shows packages, dependencies, auto generated modules :

- [Ubuntu 14 build log](https://travis-ci.org/pramodskumbhar/Tide/jobs/279214860)
- [OS X build log](https://travis-ci.org/pramodskumbhar/Tide/jobs/279214861)

With this Tide is built with 3 different GCC versions, Clang, Intel with MPICH, OpenMPI and Intel MPI.

#### Summary

Spack helps:

- to build multiple versions of softwares
- with multiple compilers
- with multiple dependencies
- for multiple architectures
- will less hassle  

> I am not suggesting/advocating Spack as new build system. I think everyone has different use cases/workflows and hence needs to be evaluated by individuals/teams to see if something that is useful.

#### References

- For Spack presentation/tutorial at BBP I started writing detailed instructions [here](https://github.com/pramodskumbhar/spack-packages) [WIP].
- Original Spack paper is [here](https://tgamblin.github.io/pubs/spack-sc15.pdf).
- Official Spack Tutorial [here](https://spack.readthedocs.io/en/latest/tutorial.html).
- Packages that I created for Tide, Deflect etc could be find [here](https://github.com/pramodskumbhar/spack-packages/compare/tide_proto?expand=1).

**Comment by hernando** [comment]
This is indeed a very interesting alternative for replacing some of the Python code that we wrote for deploying the env modules in the vizcluster from Jenkins or even just for building software in your own home. Given what I know from nix and after reading this post, If I had to choose between one or the other to replace what we already have (which will have to be replaced) I'd go with Spack.
That said, one question that comes to my mind, and which could be a criticism from Adrien, is how can you tell Spack to compile and install software using RPATH instead of requiring this evergrowing strings in LD_LIBRARY_PATH. I don't know how much is this a real concern, but I remember being pointed at this issue.
One thing that I'd avoid doing is to add compilation options to CMake in the Package config. This brings us back to the discussion about having a common CMake or not. I'd still advocate for a common set of CMake scripts for all projects that considers the problems that you raised regarding multiple compilers, architectures and optimization profiles, so the configuration code can choose the right compilation flags based on cmake options and the target system. Having this logic in CMake makes it more reusable than in the packaging system (because a packaging system is not a build system, it just give options to the build system).

**Comment by pramodskumbhar** [comment]
> That said, one question that comes to my mind, and which could be a criticism from Adrien, is how can you tell Spack to compile and install software using RPATH instead of requiring this evergrowing strings in LD_LIBRARY_PATH.

rpath'ing dependencies is common feature. Like in Nix, all dependencies of package  in Spack also get rpath'ed. 

Oh, confusion might be due to `LD_LIBRARY_PATH` in module file. That is for end users of modules if they require (and not for packages that we build, every build is handled via rpath).


> One thing that I'd avoid doing is to add compilation options to CMake in the Package config. This brings us back to the discussion about having a common CMake or not. I'd still advocate for a common set of CMake scripts for all projects that considers the problems that you raised regarding multiple compilers, architectures and optimization profiles, so the configuration code can choose the right compilation flags based on cmake options and the target system. Having this logic in CMake makes it more reusable than in the packaging system

Yes agree! If you guys have `CMake/common` across all projects to handle those settings, there is no reason to mix those in package recipe.

One thing though about : `CMAKE_COMMON_USE_CXX03_ABI`

Here was situation : I was trying to build Tide by "selectively" loading modules from `BBPCACHE/viz/env/...` and Tide compilation was failing with weird link errors. I had no idea that `CMake/common` expects `CMAKE_COMMON_USE_CXX03_ABI` env variable to be set. And in your case that is being set by meta module `BBPCACHE/viz/env/...`. As non-viz member, it was annoying 30 minutes to figure out what's going on :). Hence I added those in package recipe.

>  If I had to choose between one or the other to replace what we already have (which will have to be replaced) I'd go with Spack.

I will only `suggest` to `"evaluate"` it as one option. Anyone with some python knowledge could get good understanding of whole system in 3-4 days (from above reference). If it seems useful then one can try few simple packages.

**Comment by pramodskumbhar** [comment]
@rdumusc : I am closing this now as it was just for demo purpose and done with presentation :)
I will push some of the packages upstream (in case package like zeroeq is used by others).

**Pull request closed without merging**
