### PR TITLE
fix for travis build + replace obosolete methods

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Comment by ppodhajski** [comment]
we still use Qt 5.9 for non-travis builds and sizeInBytes was introduced in Qt 5.10 only so we will go with `-Wno-deprecated-declarations` for the time being

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by karjonas** [comment]
What about using an ifdef looking at the qt version?

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
